name: hng
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  change_app_package_name: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  url_launcher: ^6.0.9

  # Stacked
  stacked: ^2.1.8
  stacked_services: ^0.8.6
  hexcolor: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.4.6
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/background/bga.png
    - assets/logo/zuri_chat_logo.png
    - assets/background/appBarLogo.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
