name: hng
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.0.6+10
  analyzer: null
  cached_network_image: ^3.1.0
  centrifuge: ^0.6.0
  connectivity_plus: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  emoji_picker_flutter: ^1.0.7
  flutter:
    sdk: flutter
  flutter_appavailability: ^0.0.21
  flutter_chips_input: ^1.10.0
  flutter_hooks: ^0.17.0
  flutter_keyboard_visibility: ^5.0.3
  flutter_parsed_text: ^2.2.1
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.1.0
  freezed_annotation: null
  google_fonts: ^2.1.0
  grouped_list: ^4.1.0
  hexcolor: ^2.0.5
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  json_annotation: ^4.0.1
  logger: ^1.1.0
  meta: ^1.3.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  overlay_support: ^1.2.1
  page_view_dot_indicator: ^1.0.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.7
  stacked: ^2.1.8
  stacked_hooks: ^0.2.1
  stacked_services: ^0.8.6
  stacked_themes: ^0.3.6
  url_launcher: ^6.0.9
  velocity_x: ^3.3.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  mockito: null
  stacked_generator: null

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/zuri_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/background/
    - assets/icons/
    - assets/channel_page/
    - assets/plugin_icons/
    - assets/icons/emojiHands/
    - assets/icons/svg_icons/

  fonts:
    - family: ZapIcon
      fonts:
        - asset: assets/fonts/zap_icon.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Black.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #