name: zurichat
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.1.0
  # DO NOT CHANGE CENTRIFUGE FROM ^0.6.0!!!!!!!!!!!!!!.
  centrifuge: ^0.9.2
  connectivity_plus: ^3.0.2
  connectivity_plus_web: null
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  emoji_picker_flutter: ^1.0.7
  flutter:
    sdk: flutter
  appcheck: ^1.0.6
  flutter_chips_input: ^2.0.0
  flutter_hooks: ^0.18.5+1
  flutter_keyboard_visibility: ^5.0.3
  flutter_localizations:
    sdk: flutter
  flutter_parsed_text: ^2.2.1
  flutter_screenutil: ^5.0.0+2
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.2.1
  freezed_annotation: null
  google_fonts: ^3.0.1
  grouped_list: ^5.1.2
  hexcolor: ^3.0.1
  http_parser: ^4.0.0
  image_picker: ^0.8.4+1
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  json_annotation: ^4.0.1
  logger: ^1.1.0
  meta: ^1.3.0
  modal_progress_hud_nsn: ^0.3.0
  overlay_support: ^2.0.1
  observable_ish: ^4.0.6
  page_view_dot_indicator: ^2.0.1
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.7
  simple_moment: ^1.1.1
  stacked: ^3.0.0
  stacked_hooks: ^0.2.1
  stacked_services: ^0.9.8
  stacked_themes: ^0.3.6
  uni_links: ^0.5.1
  url_launcher: ^6.1.6
  velocity_x: ^3.3.0
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: null
  mockito: null
  stacked_generator: null

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/zuri_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/background/
    - assets/icons/
    - assets/channel_page/
    - assets/plugin_icons/
    - assets/icons/emojiHands/
    - assets/icons/svg_icons/
    - assets/language/

  fonts:
    - family: ZapIcon
      fonts:
        - asset: assets/fonts/zap_icon.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Black.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #