name: hng
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.7
  stacked: ^2.1.8
  stacked_services: ^0.8.6
  stacked_themes: ^0.3.6
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/background/bga.png
    - assets/logo/zuri_chat_logo.png
    - assets/background/appBarLogo.png
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
